[project]
name = "randq"
version = "0.0.3"
description = "This CLI draws a name and question repeatedly until the user choose to stop"
readme = "README.md"
authors = [
    { name = "Yun Zhou", email = "yun.zhou@mcmaster.ca" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
randq = "randq.cli:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
